##
# Command Center
#
# @file
# @version 0.1
terminal:
	gnome-terminal
firefox:
	firefox
chrome:
	google-chrome
emacs:
	emacs
element:
	element-desktop
inventory:
	~/cloud-inv
titan:
	~/titan
passbolt:
	~/.key
files:
	nemo



# end
